import { useIntl } from "react-intl"
import { NextPage } from "next"
import Head from "next/head"

import IntlLink from "@components/IntlLink"

import s from "@styles/pages/Home.module.sass"

const Home: NextPage = () => {
  const intl = useIntl()
  return (
    <div className={s.container}>
      <Head>
        <title>Anclaev</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={s.main}>
        <IntlLink href="/">
          {intl.formatMessage({ defaultMessage: "Hello, world!" })}
        </IntlLink>
      </main>

      <footer className={s.footer}>footer</footer>
    </div>
  )
}

export default Home
